spring.datasource.url=jdbc:h2:file:~/ecommercedb
# Stores H2 database in a file so data persists after restart

spring.datasource.driver-class-name=org.h2.Driver
# Defines the driver used to connect to H2 database

spring.datasource.username=ecommerce
# Username for accessing the H2 database

spring.datasource.password=Mahesh@101
# Password for accessing the H2 database

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Informs Hibernate to generate SQL compatible with H2

spring.jpa.hibernate.ddl-auto=update
# Automatically creates or updates tables based on entities

spring.jpa.show-sql=true
# Prints executed SQL queries in the console

spring.jpa.properties.hibernate.format_sql=true
# Formats SQL queries for better readability

spring.h2.console.enabled=true
# Enables the H2 database web console

spring.h2.console.path=/h2-console
# Sets the URL path to access H2 console in browser